kind: pipeline
name: default

steps:
- name: publish_frontend
  image: plugins/docker
  settings:
    repo: wugge/wug.ge
    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password#
    dockerfile: 'docker/frontend/Dockerfile'
    context: 'frontend'
  when:
    branch:
      - feat/api-base
- name: publish_api
  image: plugins/docker
  settings:
    repo: wugge/wug.ge-api
    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: 'docker/api/Dockerfile'
  when:
    branch:
      - feat/api-base
- name: deploy
  image: docker/compose
  when:
    branch:
      - main
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose.prod.yml down && docker-compose -f docker-compose.prod.yml pull && docker-compose -f docker-compose.prod.yml up -d
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock