kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: wugge/wug.ge
    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
      - main
- name: deploy
  image: docker/compose
  when:
    branch:
      - main
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose.prod.yml down && docker-compose -f docker-compose.prod.yml pull && docker-compose -f docker-compose.prod.yml up -d
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock