version: '3.2'

services:
  web:
    image: wugge/wug.ge-frontend:latest
    container_name: wugge-frontend
    restart: "unless-stopped"
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wugge-frontend.rule=Host(`wug.ge`)"
      - "traefik.http.services.wugge-frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.wugge-frontend.entrypoints=websecure"
      - "traefik.http.routers.wugge-frontend.tls=true"
  api:
    image: wugge/wug.ge-api:latest
    container_name: wugge-api
    restart: "unless-stopped"
    expose:
      - 3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wugge-api.rule=Host(`wug.ge`) && (Path(`/api/`) || PathPrefix(`/api/contact/**`))"
      - "traefik.http.services.wugge-api.loadbalancer.server.port=3001"
      - "traefik.http.routers.wugge-api.middlewares=wugge-api"
      - "traefik.http.middlewares.wugge-api.replacepathregex.regex=^/api/(.*)"
      - "traefik.http.middlewares.wugge-api.replacepathregex.replacement=/$$1"
      - "traefik.http.routers.wugge-api.tls=true"
      - "traefik.http.routers.wugge-api.entrypoints=websecure"

    environment:
      - "EXPRESS_PORT=3001"

networks:
  default:
    external:
      name:
        traefik_default