version: '3.2'

services:
  web:
    image: wugge/wug.ge
    container_name: wugge
    restart: "unless-stopped"
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wugge.rule=Host(`wug.ge`)"
      - "traefik.http.services.wugge.loadbalancer.server.port=3000"
networks:
  default:
    external:
      name:
        traefik_default