version: '3.2'

services:
  web:
    image: wugge/wug.ge:latest
    container_name: wugge
    restart: "unless-stopped"
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wugge.rule=Host(`wug.ge`)"
      - "traefik.http.services.wugge.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.wugge.redirectregex.regex=^http://wug.ge/(.*)"
      - "traefik.http.middlewares.php-apache-www-https-redirect.redirectregex.replacement=https://wug.ge/$${1}"
networks:
  default:
    external:
      name:
        traefik_default